apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- vault-namespace.yaml

helmCharts:
  - name: vault
    releaseName: vault
    namespace: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.29.1  # Specify the desired version
    valuesInline:
      server:
        dev:
          enabled: true
