apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- vault-namespace.yaml

helmCharts:
  - name: vault
    releaseName: vault
    namespace: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.29.1
    valuesInline:
      server:
        dev:
          enabled: true
        
        # dataStorage:
        #   enabled: true
        #   size: 100Mi
        #   storageClass: "standard" 

        # standalone:
        #   enabled: true
        #   config: |
        #     storage "raft" {
        #       path = "/vault/data"
        #     }

        #     listener "tcp" {
        #       address     = "0.0.0.0:8200"
        #       tls_disable = true
        #     }

        #     ui = true

# set dev: enabled to false for HA mode and uncomment the part.
# Deal with unsealing of vault.