apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx-gateway

resources:
  - namespace.yaml
  - "https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v1.6.2"
  - https://raw.githubusercontent.com/nginx/nginx-gateway-fabric/v1.6.2/deploy/crds.yaml
  - nginx-fabric-deploy.yaml
