apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml
- https://raw.githubusercontent.com/nginxinc/nginx-gateway-fabric/main/deploy/crds.yaml