apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  # Slack service configuration
  service.slack: |
    token: $slack-token
    username: argocd
    icon: ":rocket:"

  # Trigger for application deletion (updated)
  trigger.on-delete: |
    - when: app.metadata.deletionTimestamp != nil
      send: [app-delete-slack]
    - when: app.status.health.status == "Missing"
      send: [app-delete-slack]

  # Trigger for sync failure
  trigger.on-sync-failed: |
    - when: app.status.operationState != nil && app.status.operationState.phase in ['Failed', 'Error']
      send: [app-sync-failed-slack]

  # Trigger for sync success
  trigger.on-sync-succeeded: |
    - when: app.status.operationState != nil && app.status.operationState.phase == "Succeeded" && app.status.sync.status == "Synced"
      send: [app-sync-success-slack]

  # Template for application deletion (updated with safe revision check)
  template.app-delete-slack: |
    message: |
      *Application Deleted:* _{{.app.metadata.name}}_
      *Repository:* `{{.app.spec.source.repoURL}}`
      *Last Revision:* `{{if .app.status.sync.revision}}{{.app.status.sync.revision}}{{else}}-{{end}}`
      *Deletion Detected At:* {{if .context.timestamp}}{{.context.timestamp}}{{else}}{{now}}{{end}}

  # Template for sync failure
  template.app-sync-failed-slack: |
    message: |
      *Application:* _{{.app.metadata.name}}_
      *Sync Status:* ❌ _{{.app.status.sync.status}}_
      *Repository:* `{{.app.spec.source.repoURL}}`
      *Revision:* `{{.app.status.sync.revision}}`
      *Commit Author:* _{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}_
      *Commit Message:*  
       {{(call .repo.GetCommitMetadata .app.status.sync.revision).Message}}
      *Commit Date:* {{(call .repo.GetCommitMetadata .app.status.sync.revision).Date}}

  # Template for sync success
  template.app-sync-success-slack: |
    message: |
      *Application:* _{{.app.metadata.name}}_
      *Sync Status:* ✅ _{{.app.status.sync.status}}_
      *Repository:* `{{.app.spec.source.repoURL}}`
      *Revision:* `{{.app.status.sync.revision}}`
      *Commit Author:* _{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}_
      *Commit Message:*  
       {{(call .repo.GetCommitMetadata .app.status.sync.revision).Message}}
      *Commit Date:* {{(call .repo.GetCommitMetadata .app.status.sync.revision).Date}}
