# apiVersion: v1
# kind: Secret
# metadata:
#     name: argocd-notifications-secret
# stringData:
#     slack-token: #add notification token

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-notifications
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: production-devops-project-secret
  data:
  - secretKey: slack-token
    remoteRef:
      key: "argo"
      property: "slack-token"
