  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: argocd-notifications-cm
  data:
    service.slack: |
      token: $slack-token
      username: argocd
      icon: ":rocket:"

    trigger.on-delete: |
      - when: app.status.health.status == "Missing"
        send: [app-delete-slack]

    trigger.on-sync-failed: |
      - when: app.status.operationState != nil && app.status.operationState.phase == "Failed"
        send: [app-sync-failed-slack]

    trigger.on-sync-succeeded: |
      - when: app.status.operationState != nil && app.status.operationState.phase == "Succeeded"
        send: [app-sync-success-slack]

    template.app-delete-slack: |
      message: |
        *Application Deleted:* _{{.app.metadata.name}}_
        *Repository:* `{{.app.spec.source.repoURL}}`
        *Last Revision:* `{{.app.status.sync.revision}}`
        *Deletion Detected At:* {{if .context.timestamp}}{{.context.timestamp}}{{else}}{{now}}{{end}}

    template.app-sync-failed-slack: |
      message: |
        *Application:* _{{.app.metadata.name}}_
        *Sync Status:* ❌ _{{.app.status.sync.status}}_
        *Repository:* `{{.app.spec.source.repoURL}}`
        *Revision:* `{{.app.status.sync.revision}}`
        *Commit Author:* _{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}_
        *Commit Message:*  
        {{(call .repo.GetCommitMetadata .app.status.sync.revision).Message}}
        *Commit Date:* {{(call .repo.GetCommitMetadata .app.status.sync.revision).Date}}

    template.app-sync-success-slack: |
      message: |
        *Application:* _{{.app.metadata.name}}_
        *Sync Status:* ✅ _{{.app.status.sync.status}}_
        *Repository:* `{{.app.spec.source.repoURL}}`
        *Revision:* `{{.app.status.sync.revision}}`
        *Commit Author:* _{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}_
        *Commit Message:*  
        {{(call .repo.GetCommitMetadata .app.status.sync.revision).Message}}
        *Commit Date:* {{(call .repo.GetCommitMetadata .app.status.sync.revision).Date}}