# apiVersion: v1
# kind: Secret
# metadata:
#   name: production-devops-project-secret
# stringData:
#   url: https://github.com/utsab818/PDP
#   username: utsab12312
#   password: # add your token

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argo-git
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: production-devops-project-secret
  data:
  - secretKey: url
    remoteRef:
      key: "argo"
      property: "url"
  - secretKey: username
    remoteRef:
      key: "argo"
      property: "username"
  - secretKey: password
    remoteRef:
      key: "argo"
      property: "password"