apiVersion: v1
kind: Secret
metadata:
  name: production-devops-project-secret
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/utsab818/PDP             
  password: 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             
  username: production-app                                   
  