apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: postgres
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backend-database-credentials
  data:
  - secretKey: DB_HOST
    remoteRef:
      key: "dev"
      property: "db-host"
  - secretKey: DB_USER
    remoteRef:
      key: "dev"
      property: "db-user"
  - secretKey: DB_PASSWORD
    remoteRef:
      key: "dev"
      property: "db-password"
  - secretKey: DB_NAME
    remoteRef:
      key: "dev"
      property: "db-name"