apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: postgres
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: cnpg-credentials
  data:
  - secretKey: username
    remoteRef:
      key: "dev"
      property: "username"
  - secretKey: password
    remoteRef:
      key: "dev"
      property: "password"