apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres-namespace.yaml
- https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.19/releases/cnpg-1.19.6.yaml
- postgres-cluster.yaml
- vault-secret.yaml
- secret-store.yaml
- externalSecret.yaml