apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgresql
  namespace: postgres
spec:
  instances: 1
  # CloudNativePG will automatically provision a Persistent Volume (PV) for this storage.
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: false # If set to true, it would enable Prometheus monitoring for PostgreSQL metrics.
  bootstrap:
    initdb:
      database: todos
      owner: utsab
      secret:
        name: cnpg-credentials
      postInitApplicationSQL:
        - |
          CREATE TABLE IF NOT EXISTS todos (
            id SERIAL PRIMARY KEY,
            title TEXT NOT NULL,
            completed BOOLEAN DEFAULT FALSE
          );
        - |
          GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.todos TO utsab;
        - |
          GRANT ALL PRIVILEGES ON TABLE public.todos TO utsab;
        - |
          GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.todos_id_seq TO utsab;