apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocdnotification
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocdnotification
    notifications.argoproj.io/subscribe.on-delete.slack: argocdnotification
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    path: platform-apps/external-secret-operator
    repoURL: https://github.com/utsab818/PDP.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false