name: Build, Scan & Push Docker Image for frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'app/frontend/**'

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        working-directory: app/frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }} .

      - name: Scan image with Trivy (SCA + Vuln scan)
        uses: aquasecurity/trivy-action@master
        if: always()
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
          exit-code: '0'  # fail the pipeline if CRITICAL vulnerabilities are found by setting it to '1'
          severity: 'CRITICAL'
          format: 'table'

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
